# Generated by Django 4.2.5 on 2023-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bez_dni', models.CharField(max_length=20)),
                ('bez_izena', models.CharField(max_length=30)),
                ('bez_abizena', models.CharField(max_length=50)),
                ('bez_telefonoa', models.CharField(max_length=20)),
                ('bez_email', models.CharField(max_length=50)),
                ('bez_helbidea', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Bideojokua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(max_length=50)),
                ('bid_izena', models.CharField(max_length=100)),
                ('bid_generoa', models.CharField(max_length=100)),
                ('bid_hizkuntza', models.CharField(max_length=50)),
                ('bid_irteeradata', models.DateField()),
                ('bid_adinminimoa', models.IntegerField()),
                ('bid_sinopsia', models.CharField(max_length=250)),
            ],
        ),
    ]
