# Generated by Django 3.1.4 on 2023-10-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=25)),
                ('abizena', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Mahaia',
            fields=[
                ('zenbakia', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('solairua', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Alokairua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alokairu_data', models.DateField(null=True)),
                ('alokairu_ordua', models.CharField(max_length=10)),
                ('bezero_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahaiAlokairua.bezeroa')),
                ('mahai_zenbakia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahaiAlokairua.mahaia')),
            ],
        ),
    ]
