# Generated by Django 4.2.5 on 2023-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahaiAlokairua', '0002_remove_mahaia_solairua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alokairua',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
